const ordersInitialState = [
  { 
    id: 1, 
    customerName: 'John Doe', 
    orderDate: '2024-01-01', 
    status: 'Pending',
    price: 10,  // Product price
    category: 'Category A',  // Product category
    numberOfItems: 2,  // Number of items ordered
    productName: 'Product 1',  // Product name
    productId: 1,  // Product ID
    productDescription: 'Lorem ipsum dolor sit amet',  // Product description
    customerRating: 4  // Customer rating (between 1-5)
  },
  { 
    id: 2, 
    customerName: 'Jane Smith', 
    orderDate: '2024-02-02', 
    status: 'Shipped',
    price: 20,
    category: 'Category B',
    numberOfItems: 1,
    productName: 'Product 2',
    productId: 2,
    productDescription: 'Consectetur adipiscing elit',
    customerRating: 5
  },
  { 
    id: 3, 
    customerName: 'Alice Johnson', 
    orderDate: '2024-03-03', 
    status: 'Completed',
    price: 15,
    category: 'Category C',
    numberOfItems: 3,
    productName: 'Product 3',
    productId: 3,
    productDescription: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
    customerRating: 3
  },
  { 
    id: 4, 
    customerName: 'Michael Brown', 
    orderDate: '2024-01-04', 
    status: 'no',
    price: 12,
    category: 'Category D',
    numberOfItems: 2,
    productName: 'Product 4',
    productId: 4,
    productDescription: 'Ut enim ad minim veniam',
    customerRating: 2
  },
  { 
    id: 5, 
    customerName: 'Emma Davis', 
    orderDate: '2024-05-05', 
    status: 'Shipped',
    price: 18,
    category: 'Category B',
    numberOfItems: 1,
    productName: 'Product 5',
    productId: 5,
    productDescription: 'Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
    customerRating: 4
  },
  { 
    id: 6, 
    customerName: 'David Wilson', 
    orderDate: '2024-01-06', 
    status: 'yes',
    price: 25,
    category: 'Category C',
    numberOfItems: 4,
    productName: 'Product 6',
    productId: 6,
    productDescription: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
    customerRating: 5
  },
  { 
    id: 7, 
    customerName: 'Olivia Martinez', 
    orderDate: '2024-01-07', 
    status: 'Pending',
    price: 30,
    category: 'Category A',
    numberOfItems: 3,
    productName: 'Product 7',
    productId: 7,
    productDescription: 'Excepteur sint occaecat cupidatat non proident',
    customerRating: 3
  },
  { 
    id: 8, 
    customerName: 'Noah Taylor', 
    orderDate: '2024-05-08', 
    status: 'Shipped',
    price: 22,
    category: 'Category B',
    numberOfItems: 2,
    productName: 'Product 8',
    productId: 8,
    productDescription: 'Sunt in culpa qui officia deserunt mollit anim id est laborum',
    customerRating: 4
  },
  { 
    id: 9, 
    customerName: 'Sophia Garcia', 
    orderDate: '2024-02-09', 
    status: 'Completed',
    price: 17,
    category: 'Category C',
    numberOfItems: 1,
    productName: 'Product 9',
    productId: 9,
    productDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium',
    customerRating: 5
  },
  { 
    id: 10, 
    customerName: 'Liam Rodriguez', 
    orderDate: '2024-03-10', 
    status: 'go',
    price: 14,
    category: 'Category A',
    numberOfItems: 5,
    productName: 'Product 10',
    productId: 10,
    productDescription: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit',
    customerRating: 2
  },
  { 
    id: 11, 
    customerName: 'Isabella Martinez', 
    orderDate: '2024-01-11', 
    status: 'Shipped',
    price: 21,
    category: 'Category B',
    numberOfItems: 2,
    productName: 'Product 11',
    productId: 11,
    productDescription: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet',
    customerRating: 3
  },
  { 
    id: 12, 
    customerName: 'William Brown', 
    orderDate: '2024-01-12', 
    status: 'po',
    price: 28,
    category: 'Category C',
    numberOfItems: 3,
    productName: 'Product 12',
    productId: 12,
    productDescription: 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur',
    customerRating: 4
  },
  { 
    id: 13, 
    customerName: 'Amelia Rodriguez', 
    orderDate: '2024-04-13', 
    status: 'Pending',
    price: 16,
    category: 'Category A',
    numberOfItems: 1,
    productName: 'Product 13',
    productId: 13,
    productDescription: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores',
    customerRating: 5
  },
  { 
    id: 14, 
    customerName: 'James Johnson', 
    orderDate: '2024-01-14', 
    status: 'Shipped',
    price: 24,
    category: 'Category B',
    numberOfItems: 4,
    productName: 'Product 14',
    productId: 14,
    productDescription: 'Et harum quidem rerum facilis est et expedita distinctio',
    customerRating: 3
  },
  { 
    id: 15, 
    customerName: 'Charlotte Wilson', 
    orderDate: '2024-08-15', 
    status: 'Completed',
    price: 31,
    category: 'Category C',
    numberOfItems: 2,
    productName: 'Product 15',
    productId: 15,
    productDescription: 'Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus',
    customerRating: 4
  },
  { 
    id: 16, 
    customerName: 'Benjamin Taylor', 
    orderDate: '2024-01-16', 
    status: 'Pending',
    price: 19,
    category: 'Category A',
    numberOfItems: 3,
    productName: 'Product 16',
    productId: 16,
    productDescription: 'Omnis voluptas assumenda est, omnis dolor repellendus',
    customerRating: 2
  },
  { 
    id: 17, 
    customerName: 'Ava Davis', 
    orderDate: '2024-09-17', 
    status: 'Shipped',
    price: 23,
    category: 'Category B',
    numberOfItems: 1,
    productName: 'Product 17',
    productId: 17,
    productDescription: 'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae',
    customerRating: 3
  },
  { 
    id: 18, 
    customerName: 'Mason Thomas', 
    orderDate: '2024-012-18', 
    status: 'Completed',
    price: 26,
    category: 'Category C',
    numberOfItems: 2,
    productName: 'Product 18',
    productId: 18,
    productDescription: 'Itaque earum rerum hic tenetur a sapiente delectus',
    customerRating: 5
  },
  { 
    id: 19, 
    customerName: 'Harper Brown', 
    orderDate: '2024-011-19', 
    status: 'Pending',
    price: 33,
    category: 'Category A',
    numberOfItems: 3,
    productName: 'Product 19',
    productId: 19,
    productDescription: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam',
    customerRating: 4
  },
  { 
    id: 20, 
    customerName: 'Evelyn Martinez', 
    orderDate: '2024-01-20', 
    status: 'Shipped',
    price: 29,
    category: 'Category B',
    numberOfItems: 1,
    productName: 'Product 20',
    productId: 20,
    productDescription: 'Dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident',
    customerRating: 5
  },
];

export default ordersInitialState;
